ALTER TABLE users ADD COLUMN IF NOT EXISTS cep text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS street text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS number text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS complement text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS neighborhood text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS city text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS state text;
